server:
  port: 720

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: redis
    timeout: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cnblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
# MyBatis
#mybatis:
#  type-aliases-modules: com.icss.cnblog.entity
#  mapper-locations: classpath:/mybatis/*/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yxyt/*/mapper/*.xml
  # 如果是放在resource目录 classpath:/mybatis/*.xml
  mapper-locations: classpath:/mybatis/*/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.icss.cnblog.entity;com.icss.cnblog.modules.blog.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true


# sql日志
logging:
  level:
    com.icss.cnblog: debug


shiro:
  cache:
    # 是否启用redis作为缓存
    enable-redis: false